version: '2'
services:
  # In case of docker use "jdbc:mysql://ponut_mysql:3306/ponut" as connection string
  db:
    container_name: ponut_mysql
    build: ./docker/mysql
    ports:
      - "3309:3309"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ponut
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  java:
    container_name: ponut_java
    build: ./docker/java
    ports:
      - "4567:4567"
    links:
      - db
    volumes:
      - .:/opt/apps/ponut
    environment:
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ponut
      MYSQL_USER: root
      MYSQL_HOST: ponut_mysql
    tty: true